
@startuml

  :Owner: as Owner <<Human>>
  actor Voter <<Human>>
  actor Processor <<Human>>
  actor Data_Auditor <<Human>>
  actor Helpdesk <<Human>>
  actor Collection_Service <<Server>>
  actor Registration_Service <<Server>>
  actor Authentication_Service <<Server>>
  actor Signing_Service <<Server>>



@enduml
