@startuml

left to right direction

package "Collector Service" {
    [Storage] as collector
    [Log] as log
    [Eligibility] as elig
    [Verification] as verif
    [Admin] as adminc


interface "Election definition" as i_define
interface "Ballot export" as i_export
interface "Voting" as i_vote
interface "Verification" as i_verify
interface "Choice list" as i_cls
interface "Command line" as i_localadmin
interface "Remote management" as i_remoteadmin
interface "Monitoring" as i_monitor
interface "Helpdesk" as i_helpdesk



}

elig -- collector
verif -- collector

verif ..> log
elig ..> log
collector ..> log

package "Environment Services" {
    [Registration Service] as tsa
    [Authentication Service] as auth
    [Signing Service] as sign
}

[Lists] as voterlist
[Backup] as backup


collector ..> tsa

i_vote ..> sign
i_cls ..> auth

interface "Backup" as i_backup
interface "List updates" as i_voterlist

elig -up- i_cls
elig -up- i_vote
verif -up- i_verify


collector -down- i_localadmin
log -down- i_helpdesk
log -down- i_monitor
adminc -down- i_remoteadmin



adminc -down- i_define
adminc -down- i_export


voterlist -right- i_voterlist
backup -right- i_backup


collector .left.> i_backup
elig .left.> i_voterlist

@enduml
