
@startuml

title "Audit Application - offline"

usecase (Collector Service audit material import)
usecase (Counting Service audit material import)
usecase (Mixing Service audit material import)
usecase (Timestamping Service audit material import)
usecase (Conducting audit)

@enduml
