
@startuml

title "Voting Phase in hosting"

usecase (*) as UC0

note left of UC0
* Only the storage component and timestamping preserve state
* Other components are stateless - load balancing is possible
* Storage component fault tolerance - HadoopFS or byzantine?
* Definition and validation of external interfaces of online components
* Requirement for TLS usage and limiting to port 443
* HTTP is not essential but may help
endnote

package "Support" {
    usecase (Backup without stopping the voting period)
    usecase (Recovery to a clean system)
    usecase (Logging to monitoring system)
    usecase (Remote observation of system state)
    usecase (Observation of system state from command line) as UC1.5
    note left of UC1.5
    * git-style command set instead of pseudographics
    * use system solutions where possible instead of reinventing
    endnote
}

package "Pre-voting period" {
    usecase (Test voting for connection testing)
    usecase (Remote start of voting period)
}

package "Voting period" {
    usecase (Periodic update of voter lists)
    usecase (Vote storage) as UC2.2
    usecase (Responding to verification queries)
    usecase (Interim audit)
    usecase (Server consistency check)
    usecase (Gradual remote stopping of voting period)

    note left of UC2.2
    * authentication of persons
    * determination of voting right(s)
    * issuing choices
    * receiving and storing votes
    * issuing verification identifiers
    endnote

}

' at least part of the votes on Estonian soil at least once per day, may also include log data
' backup on Estonian soil must be readable

package "Post-voting period" {
    usecase (Compilation of i-voter list by polling districts)
    usecase (Export of votes from Collector Service)
    usecase (Export of audit material from Collector Service)
'    usecase (Export of audit material from timestamping service)
    usecase (Export of logs from Collector Service)
}


package "Voter activities" {
    usecase (Installing voting application from authentic source)
    usecase (Installing verification application from authentic source)
    usecase (E-voting)
    usecase (E-vote verification)
}

@enduml
