
@startuml

title "Counting Phase - offline"

package "Processor" {
    usecase (Import of signed votes)
    usecase (Import of timestamps)
    usecase (Verification - ver, ATO)
    usecase (Cancellation of repeated votes)
    usecase (List of i-voters by polling districts)

    usecase (Import of revocation applications)
    usecase (Import of revocation restoration applications)
    usecase (Anonymization)
    usecase (Export of anonymized votes)
    usecase (List of i-voters sent to counting by polling districts)
}

package "Mixing" {
    usecase (Audited random)
    usecase (Import of anonymized votes)
    usecase (Mixing of votes)
    usecase (Export of mixed votes)
    usecase (Export of mixing proof)
}

package "Counting" {
    usecase (Import of encrypted votes)
    usecase (Tallying of e-votes)
    usecase (Export of e-voting results)
    usecase (Export of decryption proof)
}

package "Key Management" {
    usecase (Activation of private key)
}

package  "Audit" {
    usecase (Collector Service audit material import)
    usecase (Counting Service audit material import)
    usecase (Timestamping Service audit material import)
    usecase (Conducting audit)
}

package "Ending the election" {
    usecase (Archiving)
    usecase (Destruction of private key and copies)
}

@enduml
