@startuml

title "Preparation Phase in office"

usecase (*) as UC0

note left  of UC0
Nuances not addressed elsewhere
* Capability to organize multiple simultaneous elections of different types
* Capability to use null authentication methods and lists
* Data format specification
* External interface and dependency specification
end note

actor Owner
actor Voter
actor Collector
actor Processor
actor Auditor
actor IDP
actor ATO
actor STO
actor Helpdesk




package "Configuration management" {
    usecase (Text management) as UC1.5
    usecase (Loading election info) as UC1.1
    usecase (Technical parameter management) as UC1.4
    usecase (Authentication service configuration) as UC1.6
    usecase (Validity confirmation service configuration) as UC1.7
    usecase (Timestamping service configuration) as UC1.8
    usecase (Configuration validation) as UC1.9
    usecase (Configuration signing) as UC1.10
    usecase (Configuration export) as UC1.11

    usecase (Defining signature creation, timestamping, and validity verification methods)

    usecase (Defining algorithm and key)

note bottom of UC1.11
Creation of signed configuration packages per component
endnote

note bottom of UC1.1
* Election
* Rules
* Voters
* Choices
* Districts
endnote

}

Owner -> UC1.10
Collector -> UC1.5

note left of UC1.9
* Existence check
* Format check
* Consistency check
endnote

note top of UC1.5
* Verification application
* Voting application
endnote


package "Key management" {
    usecase (Key pair and PIN generation) as UC2.1
    usecase (Key pair backup creation) as UC2.2
    usecase (Transport of public component to voting application) as UC2.3
    usecase (Preparation of voting application) as UC2.4

    ' some with PIN some without

    note left of UC2.1
    * MofN
    * smart card vs. HSM
    endnote

}

package "Environment preparation" {
    usecase (Installation package management) as UC3.1
    usecase (System installation) as UC3.2
    usecase (Trust list) as UC3.3
    usecase (Management of authorized person certificates)
    usecase (Loading configuration) as UC3.4
}

package "Desktop testing" {
    usecase (Key pair verification, test voting) as UC4.1
}

@enduml
