
@startuml

title "Processor"

usecase (Processor trust root loading)
usecase (Processor configuration import)
usecase (Import of signed votes)
usecase (Import of timestamps)
usecase (Verification - ver, ATO)
usecase (Cancellation of repeated votes)
usecase (List of i-voters by polling districts)
usecase (Import of revocation applications)
usecase (Import of revocation restoration applications)
usecase (Anonymization)
usecase (Export of anonymized votes)
usecase (List of i-voters sent to counting by polling districts)
usecase (Activity log)
usecase (Result log)
usecase (Vote status log)

usecase (Proof of correct repeated vote cancellation)
usecase (Proof of correct vote cancellation due to paper vote)
usecase (Proof of mixing input authenticity)

@enduml
