
@startuml

title "Key Application"

    usecase (Verification configuration import)
    usecase (Import of candidate and district lists)
    usecase (Import of encrypted votes)
    usecase (Decryption of e-votes)
    usecase (Tallying of e-votes)
    usecase (Verification of input info)
    usecase (Signing of output info)
    usecase (Export of e-voting results)
    usecase (Export of invalid ballot list)
    usecase (Export of decryption proof)
    usecase (Export of activity log)
    usecase (Vote status log)

    usecase (Key pair generation)
    usecase (Adding randomness)
    usecase (Measuring randomness)
    usecase (Certificate signing)
    usecase (Activation of private key)
    usecase (Destruction of private key and copies)

@enduml


' Application configuration
' Key generation
' Certificate issuance
' Voting result issuance
