@startuml

left to right direction

package "IVXV" {
    [Queue service] as votesorder
}

[X-Road service(xroad-service)] as xservice
[X-Road security server] as xsec

xsec --> xservice
xservice--> votesorder

@enduml
